### ISSUE TITLE
Closing tags not correct.

### ISSUE THREAD

**Issue by thakursaurabh1998** [Ramanpreet6262/rangrezz-fest-website#3]
https://github.com/Ramanpreet6262/rangrezz-fest-website/blob/077df709f26364e34a8c7ff4835ee1904db2c6eb/index.html#L114

## Also some tags like img tag doesn't need a closing tag.

**Comment by Ramanpreet6262** [comment]
Yes I resolved them .......
pls check and if it is ok, close the issue...

Thanks ...

**Comment by thakursaurabh1998** [comment]
✌🏼✌🏼✌🏼
